name: Secret deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    tags: none

jobs:
  gen_secrets:
    runs-on: ubuntu-latest
    name: Generate secrets
    steps:
      - name: gen secrets
        uses: and-fm/k8s-yaml-action@develop
        id: gen
        with:
          name: test_secrets
          namespace: grid-dev
          secrets: |-
            TEST_SECRET:${{ secrets.TEST_SECRET }}
            HELLO:${{ secrets.HELLO }}
      - name: get secrets
        run: |
          echo "${{ steps.gen.outputs.out_yaml}}"
